# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simplus_pb2 as simplus__pb2


class SimPlusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Start = channel.unary_unary(
        '/SimPlus.SimPlus/Start',
        request_serializer=simplus__pb2.WorldInfo.SerializeToString,
        response_deserializer=simplus__pb2.TeamInfo.FromString,
        )
    self.Action = channel.unary_unary(
        '/SimPlus.SimPlus/Action',
        request_serializer=simplus__pb2.Observations.SerializeToString,
        response_deserializer=simplus__pb2.Commands.FromString,
        )
    self.End = channel.unary_unary(
        '/SimPlus.SimPlus/End',
        request_serializer=simplus__pb2.Ending.SerializeToString,
        response_deserializer=simplus__pb2.Result.FromString,
        )


class SimPlusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Start(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Action(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def End(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimPlusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=simplus__pb2.WorldInfo.FromString,
          response_serializer=simplus__pb2.TeamInfo.SerializeToString,
      ),
      'Action': grpc.unary_unary_rpc_method_handler(
          servicer.Action,
          request_deserializer=simplus__pb2.Observations.FromString,
          response_serializer=simplus__pb2.Commands.SerializeToString,
      ),
      'End': grpc.unary_unary_rpc_method_handler(
          servicer.End,
          request_deserializer=simplus__pb2.Ending.FromString,
          response_serializer=simplus__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SimPlus.SimPlus', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
